permalink: pretty
plugins:
  - jekyll-feed

# Настройка 404 страницы для GitHub Pages
title: Deadlock Guides
description: Русскоязычные гайды по Deadlock
baseurl: "" 
url: "https://itstuff228.github.io"
